Frontend
Kaxuo/AuthASPNETAngular pull request #2
Opened 2020-09-22 09:52 UTC by Kaxuo

2020-09-22 22:25 UTC, Jeykairis requested changes
Please, take the time to cleanup your code before submitting a PR. 
Rename the branch and the PR as it contains code from the backend. 
Use a proper .gitignore for the backend.
Remove extra white spaces and ensure clarity and consistency of variable names to be able to remove most comments.
Finally, try to keep the code as simple as possible.

2020-09-22 22:25 UTC, jeremykairis commented on FrontEnd/src/index.html
> +    <!-- JQuery -->
You should avoid jQuery in Angular apps and use npm to add dependencies.
I checked mdbbootstrap and found their pricing annoying so it's better to learn [Angular Material](https://material.angular.io/) and [Bootstrap](https://getbootstrap.com/).

2020-09-22 22:25 UTC, jeremykairis commented on FrontEnd/src/app/components/profile-page/profile-page.component.ts
> +          }
Could you simplify this code being more generic ?

2020-09-22 22:25 UTC, jeremykairis commented on FrontEnd/src/app/components/profile-page/profile-page.component.ts
> +          });
Do you really need all these flags and separate FormGroups ?

2020-09-22 22:25 UTC, jeremykairis commented on FrontEnd/src/app/components/navbar/navbar.component.scss
> +
Remove unused code.

2020-09-22 22:25 UTC, Jeykairis commented on BackEnd/Profile/AutoMapperProfile.cs
> +            CreateMap<UpdateModel, User>();
Try to simplify the user update process to reduce mappers.

2020-09-22 22:25 UTC, Jeykairis commented on BackEnd/Migrations/UserContextModelSnapshot.cs
> +#pragma warning disable 612, 618
Why do you use this #pragma ?

2020-09-22 22:25 UTC, Jeykairis commented on BackEnd/appsettings.json
> +  },
Sensitive data should be kept out of the source control.

2020-09-24 12:39 UTC, Kaxuo commented
Everything should have been changed like you asked (except the name of the branch, I will try to be more accurate next time)

- Codes for the Profile Page has been totally changed, flags are added differently (and thus, not seen) , the "sendData" method doesn't have a "if" for each field anymore and is more generic. The FormGroup is more consice, no more FormGroup for each input field.
Sorry, I did that at first because I couldn't find a solution for a "Single Field only Input" so I just coded it the hard way.

- Added some lines in the gitignore file to ignore what needs to be ignored in the subfolder "BackEnd"

- Sensitive Data are now stored safely and can no longer be seen in the BackEnd , appsetting.json

- Deleted the UpdateModel because it wasn't needed anymore.

- #Pragma file is automatically generated when migrating and updating the database.

I hope I did everything correctly. Sorry if I took some time to do it. I got stuck trying to find a way to hide sensitive data when the solution was so simple.

Many Thanks

2020-09-24 19:50 UTC, Jeykairis requested changes
It gets better and better, continue to improve the .gitignore and cleanup white spaces to get it merged.

2020-09-24 19:50 UTC, Jeykairis commented on BackEnd/Controllers/UserController.cs
> +
Be consistent using white spaces.

2020-09-24 19:50 UTC, Jeykairis commented on BackEnd/Data/MySQLMethods.cs
> +
Take care of white spaces to make clean code.

2020-09-24 19:50 UTC, Jeykairis commented on BackEnd/Data/UserContext.cs
> +        // protected override void OnModelCreating(ModelBuilder modelBuilder)
Remove the old code.

2020-09-24 19:50 UTC, Jeykairis commented on FrontEnd/src/index.html
> +    <link
Can you use npm to add these links ?

2020-09-25 08:08 UTC, closed without merging

2020-09-25 08:13 UTC, Kaxuo commented
- White spaces have been cleanup a little bit better ( hopefully ) and made more consistent
- Sorry about unused codes, most of the times, they're here for me as a reminder that either I need to check up on that later or that it "exists" so that I could use it again somewhere else.
- Links has been removed in the index.html, they're not needed. I probably added them when trying to make MDB work when a simple npm install would have sufficed